### ISSUE TITLE
Extended json version for newer sets (BFZ,ORI) does not have line breaks after keywords.

### ISSUE THREAD

**Issue by eddie-g** [lsmoura/mtgjson#102]
Take a look at the http://mtgjson.com/json/ORI-x.json the "\n" is missing between (First strike and Renown 1.)
This is prevalent through all cards in that set for the extended version.
For <b>Consul's Lieutenant: </b>
originalText:"First strikeRenown 1 (When this creature deals combat damage to a player, if it isn't renowned, put a +1/+1 counter on it and it becomes renowned.)Whenever Consul's Lieutenant attacks, if it's renowned, other attacking creatures you control get +1/+1 until end of turn.

**Comment by lsmoura** [comment]
Hello!

Gatherer is at fault here, actually.
Check out the [Consul's Lieutenant](http://gatherer.wizards.com/Pages/Card/Details.aspx?printed=true&multiverseid=398446) on Gatherer. It has no line breaks...

But the "text" field is ok!
