### ISSUE TITLE
Oath Time!

### ISSUE THREAD

**Issue by ZeldaZach** [lsmoura/mtgjson#105]
Hey lsmoura! Something I normally do for every set (as some people seem to like it) is leave a ticket when gatherer gets updated. Just a reminder for you that Oath is up :)

Have a great day!

**Comment by lsmoura** [comment]
Thanks!

I'm checking gatherer (almost) like a hawk. If anyone spots the update before me, feel free to post here and I'll get a notification!

**Comment by ZeldaZach** [comment]
Uhh it's up already :P 
http://gatherer.wizards.com/Pages/Search/Default.aspx?set=[%22Oath%20of%20the%20Gatewatch%22]

**Comment by lsmoura** [comment]
Oh, damn...

**Comment by lsmoura** [comment]
Let the headaches begin!

http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=373743

**Comment by ZeldaZach** [comment]
Are you referring to the new mana symbol?

**Comment by lsmoura** [comment]
Precisely. Maybe I'll have to re-fetch everything?

**Comment by ZeldaZach** [comment]
Potentially. It might need a quick conversion from {1} to {c}

**Comment by lsmoura** [comment]
I'll change '{n}' to 'n times {C}'...

**Comment by ZeldaZach** [comment]
Sounds good. A full rerun seems necessary now though

**Comment by lsmoura** [comment]
I've successfully updated the mana symbols... But many cards have their text changed somehow. I'm fetching the sets again, and will update when it's done.

Sadly, it won't be today.

**Comment by ZeldaZach** [comment]
Yeah, some cards should have text changes.

Sol Ring should now be `{T}: add {C}{C} to your mana pool.` for example. Printed version text should still remain the same, though: `{T}: add {2} to your mana pool.`

**Comment by lsmoura** [comment]
Exactly! It was easier than I thought...

```
text.replace(
	/Add {([0-9]*)}/gi,
	function(full, part) {
		var ret = 'Add ';
		for (var i = 0; i < part; i++)
			ret += '{C}';
		return(ret);
	}
);
```

**Comment by ZeldaZach** [comment]
Looks about right to me, so you'll implement that for all versions now then?

Also, make sure the printed version remains the same!

**Comment by lsmoura** [comment]
I did not see this coming:

```
'Channel' (4ED) has a field 'text' mismatch: '"Until end of turn, any time you could activate a mana ability, you may pay 1 life. If you do, (Add/add) {C} to your mana pool."'
```

**Comment by ZeldaZach** [comment]
You can put an exception case in and/or keep the text capitalizations. Why don't you set up a gitter.im for MtgJson so we can chat more? :)

**Comment by rotaercz** [comment]
I've attached the Oath of the Gatewatch spoilers .json file for people that
want it a bit more quickly.

I built it using Sembiance's version on Github. I couldn't get Ismoura's
version on up and running.


When running Ismoura's version I get the following error:

/mtgjson-master/node_modules/tiptoe/index.js:21
throw args[0];
^
TypeError: Object # has no method 'gzipSync'
at Function.createDoc (/mtgjson-master/shared/shared.js:667:38)
at next (/mtgjson-master/node_modules/tiptoe/index.js:48:22)
at Object._onImmediate (/mtgjson-master/node_modules/xutil/http.js:75:82)
at processImmediate as _immediateCallback

Not sure what I need to install to solve the gzipSync problem. I tried
installing zlib but that didn't seem to help. Feel free to use this
OGW.json file for people that want it now.

**Comment by Garbee** [comment]
FYI attachments don't come through email to GitHub. You need to host it somewhere and link it.

**Comment by rotaercz** [comment]
I hosted it temporarily here:

http://goblinhammer.com/mtgjson

Right click and save link as to download the file.

**Comment by lsmoura** [comment]
Almost there, guys! =)

Fixing all trample issues, legalities, printings, etc...

**Comment by lsmoura** [comment]
If you want only OGW.json, here you go: https://gist.github.com/lsmoura/6e1a015fe900495a56c4

**Comment by rotaercz** [comment]
Any idea why I'm getting this error?

/mtgjson-master/node_modules/tiptoe/index.js:21
throw args[0];
^
TypeError: Object # has no method 'gzipSync'
at Function.createDoc (/mtgjson-master/shared/shared.js:667:38)
at next (/mtgjson-master/node_modules/tiptoe/index.js:48:22)
at Object._onImmediate (/mtgjson-master/node_modules/xutil/http.js:75:82)
at processImmediate as _immediateCallback

**Comment by Garbee** [comment]
@rotaercz Please open a specific issue about problems you are having. This issue is about getting OGW up.
