### ISSUE TITLE
Add a simple AllCards containing latest versions, OR add multiverseId to AllCards.

### ISSUE THREAD

**Issue by PAK90** [lsmoura/mtgjson#106]
Firstly, just have to say, I'm a huge fan of mtgjson, it's a real useful resource.

I've been working on a project where I want all existing cards (barring those from Un-sets) but I don't care about the set, and I want the card data to be free of duplicates. Currently I'm achieving this by copying individual set files and editing out dupicate cards and lands manually. This is a bit of a chore. My app retrieves cards by cardname so I can't use AllSets.json because it's sorted by set. AllCards.json is what I want but it doesn't have multiverseId, which is the key I use for image lookup.

So what I'm hoping for is an AllCardsRecent.json set which has the latest versions of cards, or an addition to AllCards.json where each 'printings' property has the associated multiverseId. Or alternately, an easy method to use the existing datasets to retrieve a multiverseId using only the cardname; I easily could've missed that.

Thanks :)

**Comment by lsmoura** [comment]
Are you using javascript (node) or something else?

**Comment by PAK90** [comment]
Oh, yes, I'm using reactJS, on nodeJS and npm.

**Comment by lsmoura** [comment]
Is this what you need?

https://gist.github.com/lsmoura/47e80dcb6bc55837665a

**Comment by PAK90** [comment]
Essentially, yes. I would also need a few pieces of other information that the default AllCards.json gives me (colour identity, casting cost, etc.) so would it be possible to do an AllCards combined with the data in that gist?

**Comment by lsmoura** [comment]
[Gist generator updated](https://gist.github.com/lsmoura/7126297c07afe813b0cf).The JSON file got too big (39Mb)...

**Comment by PAK90** [comment]
Perfect, thanks :)

Just so I don't screw it up, how do I run that to generate the 39mb json file?

**Comment by lsmoura** [comment]
Assuming you have nodejs installed...

* create an empty folder
* put the gist file inside (we'll call it ```pak90.js```)
* ```npm install tiptoe``` (it will complain not having package.json. Don't bother...)
* ```npm install https://github.com/mtgjson/mtgdb.git```
* ```node pak90.js```

It will download and save "AllSets-x.json" the first time you run (so it may take a while). Other runs will use the cached file.

**Comment by lsmoura** [comment]
I'm closing this issue.

If you want, you're welcome to chat with us on gitter.

[![Gitter](https://badges.gitter.im/lsmoura/mtgjson.svg)](https://gitter.im/lsmoura/mtgjson?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
