### ISSUE TITLE
SSL for the API?

### ISSUE THREAD

**Issue by Garbee** [lsmoura/mtgjson#107]
Any plans to get SSL setup for the domain? [Let's Encrypt](https://letsencrypt.org/) offers free domain validation certs. Short-lived though, so automation is needed to keep sanity. Other than that [startssl](https://www.startssl.com/) offers free domain validation certs. However, their UX last I used it was horrid.

This is just a good benefit for verifying transmissions and stopping any simple forms of manipulation of traffic ISPs may be doing.

**Comment by lsmoura** [comment]
This. I like this.

**Comment by justin-gerhardt** [comment]
The recent commits remove the http part of the url's but forgot to add https:

**Comment by lsmoura** [comment]
That's exactly the idea.

If you use http://mtgjson.com, you'll get the http:// for google fonts.

If you use https://mtgjson.com, you'll get the https:// for google fonts.

It won't work if you're using the files locally, tough. (using file:///)

**Comment by Garbee** [comment]
@lsmoura It is *best* though to **always** use HTTPS where available though. The protocol relative hack only decreases security.

If HTTPS is available, there is no reason not to take advantage of it.
