### ISSUE TITLE
huge json file difficult to import into (mongo) database

### ISSUE THREAD

**Issue by Zw3rv3r** [lsmoura/mtgjson#125]
My issues are not directly application issues but suggestions for usability improvement.

I'm trying to import allcards.json into a Mongo database as a collection to create a card search engine. Unfortunately, I encounter two problems:

1) allcards.json appears to be a json array, but it is not according to the json specs / jslint
2) allcards.json file size exceeds the 16Mb file size limit for data imports with mongoimport

Putting brackets [ ] around the json solves the first problem. Splitting up the allcards.json file into smaller files could solve the second problem but I'm still struggling at a solution at this moment. Because of the file size most editors choke on it, so I am trying to make a script that can do this streaming. Any suggestions are welcome of course :-)

Part of the problems have to do specifically with Mongo of course. But my suggestion is to (also) generate the huge allcards.json file into smaller files for more easy data import in any database, and to create the json as a valid json array for better long-term compatibility.

**Comment by leematos** [comment]
This already exists: http://mtgjson.com/sets.html

You can import each set one at a time using mongoimport probably or the other option is to write a script that reads the json and puts each card into the db to get around mongoimport's 16MB limitation. Both viable options.

**Comment by Zw3rv3r** [comment]
I didn't analyse the differences between the sets and allcards.json. So if they indeed have the same data structure with a smaller collection of the information importing the different sets sounds like a good option to me. Thank you for pointing that out.

**Comment by lsmoura** [comment]
[AllCards.json](https://mtgjson.com/json/AllCards.json) is an object and it gathers most of the information of all cards (but not all). [AllSets.json](https://mtgjson.com/json/AllSets.json) is a much more consistent way to retrieve all cards information (and their differences between sets).

As @leematos said, there is a separate json file for each set (such as [BFZ](https://mtgjson.com/json/BFZ.json) or [SOI](https://mtgjson.com/json/SOI.json)), wich is identical to the information on AllSets.json. You can get all the available sets on [SetList.json](https://mtgjson.com/json/SetList.json) (it's an array of objects).

As another method, you could also clone the mtgjson repository on github and use the data from there.
