### ISSUE TITLE
Colorless Mana affects Chaos Symbol

### ISSUE THREAD

**Issue by MickHardins** [lsmoura/mtgjson#126]
Since the code for Colorless mana is {C} now each card that had a chaos Symbol ( Planechase sets ) in is text is affected by the change.

**Comment by tracyfloyd** [comment]
MTG Salvation lists the Chaos symbol as {CHAOS}:
http://mtgsalvation.gamepedia.com/Numbers_and_symbols

Gatherer's rulings section uses a {C} code for it, though:
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=198073

So am not sure what the official code is supposed to be. {CHAOS} seems like a good, safe option though.

**Comment by lsmoura** [comment]
It's officially {CHAOS}. I'll fix it shortly. 

https://twitter.com/tabakrules/status/702271812554477568

**Comment by MickHardins** [comment]
Great! Thank you :)
Il 24 feb 2016 12:26 AM, "Sergio Moura" <notifications@github.com> ha
scritto:
