### ISSUE TITLE
Blessed vs. Cursed : BVC or DDQ ?

### ISSUE THREAD

**Issue by mirandir** [lsmoura/mtgjson#128]
The new Duel Decks has the BVC code on mtgjson, but the code DDQ [is printed on the cards](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=409653).

Shouldn't we use the printed code ?

**Comment by lsmoura** [comment]
My bad.

You're right. We should. The hashtag on [this link](http://magic.wizards.com/en/articles/archive/feature/announcing-duel-decks-blessed-vs-cursed-2015-11-02) misleaded me.

Fixing right now.
