### ISSUE TITLE
No method gzipSync - hangs in shared.js

### ISSUE THREAD

**Issue by robbintt** [lsmoura/mtgjson#132]
I was able to get things up and running, and was able to dump the HTML that's choking here. I can't figure out why this is happening.

```
$ node --harmony buildSet.js BFZ
Doing sets: BFZ
====================================================================================================================


Ripping Set: Battle for Zendikar
Getting card lists...
Battle for Zendikar
Requesting from web: http://gatherer.wizards.com/Pages/Search/Default.aspx?output=checklist&sort=cn%2B&action=advanced&special=true&set=%5B%22Battle%20for%20Zendikar%22%5D&page=0

/home/robbintt/clonolith/mtgjson/node_modules/tiptoe/index.js:21
                                throw args[0];
                                          ^
TypeError: Object #<Object> has no method 'gzipSync'
    at Function.createDoc (/home/robbintt/clonolith/mtgjson/shared/shared.js:682:38)
    at next (/home/robbintt/clonolith/mtgjson/node_modules/tiptoe/index.js:48:22)
    at Object._onImmediate (/home/robbintt/clonolith/mtgjson/node_modules/xutil/http.js:75:82)
    at processImmediate [as _immediateCallback] (timers.js:363:15)

$ node -v
v0.10.43
```

**Comment by lsmoura** [comment]
It MAY be the node version. Any chance you can update it? Here's mine:

```
$ node -v
v5.0.0
```

**Comment by peardox** [comment]
Quick Q - Ubuntu 14.04?

If so, I have exactly the same problem

I'm building node from source to see if that fixes things

If anything else - soz

**Comment by robbintt** [comment]
Yes, ubuntu 14.04

On Wednesday, March 30, 2016, peardox <notifications@github.com> wrote:

> Quick Q - Ubuntu 14.04?
>
> If so, I have exactly the same problem
>
> I'm building node from source to see if that fixes things
>
> If anything else - soz
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/lsmoura/mtgjson/issues/132#issuecomment-203304803>
>


-- 
(Sent from cellphone)

**Comment by peardox** [comment]
That was a polava but I've got things further

First off kill node completely...

apt-get purge nodejs npm

Now build from source (I'm gonna one I know works)

apt-get install git
git clone -b v0.12.7-release

[Twiddle thumbs]

cd node
./configure
make

[Twiddle thumbs]

sudo make install

Go back to your mtgjson directory and

rm -rf node_modules

node install

Change const to var on 1539 if rip.js (validColors)

This now works UNTIL it gets to printings for ORI

BFZ went fine though

It'll screw up at end of first run, simply run it again and it completes

OGW testing next then find out what's wrong with ORI

**Comment by peardox** [comment]
OGW OK - M15 next

Will look into ORI later

BFN - hope this helps a bit

**Comment by lsmoura** [comment]
This is not as fixed as I want it to be, but it will do for now.

Since commit 7084614fe222c5dc89e8abae7f6d4ef2eac6283b, you can change the line on top of shared.js from

```javascript
exports.cache = cache(path.join(__dirname, '..', 'cache'), { compress: true });
```

to

```javascript
exports.cache = cache(path.join(__dirname, '..', 'cache'), { compress: false });
```

With this, gzip will be completely ignored and the files will be saved without compression. Make sure to `npm update` after pulling the repository to download the cache module and its dependencies.

**Comment by lsmoura** [comment]
I believe that, with this, both @robbintt and @peardox issues are resolved. If gzip keeps getting on your way, please reopen this. If it's something else, please open a new issue.

**Comment by peardox** [comment]
With Node 5.0.0 / 5.9.1 you get the stuff below

I'll try an earlier version til it works

==================================================

simon@ubuntu:~/mtgjson$ node install > nreport.txt
module.js:341
    throw err;
    ^

Error: Cannot find module '/home/simon/mtgjson/install'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3
simon@ubuntu:~/mtgjson$ npm install > nreport.txt
stdfns.c: In function 'mutils_memcpy':
stdfns.c:227:19: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  if ((n < 16) || ((mutils_word32)ptr1 & 0x3) || ((mutils_word32)ptr2
                   ^
stdfns.c:227:50: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  if ((n < 16) || ((mutils_word32)ptr1 & 0x3) || ((mutils_word32)ptr2
                                                  ^
/usr/share/unicode/UnicodeData.txt not found.
/usr/share/unicode-data/UnicodeData.txt not found.
UnicodeData.txt not found.
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@0.3.8
simon@ubuntu:~/mtgjson$ less nreport.txt
simon@ubuntu:~/mtgjson$ cd node_modules
simon@ubuntu:~/mtgjson/node_modules$ ln -s ../shared/C.js
simon@ubuntu:~/mtgjson/node_modules$ ln -s ../shared/shared.js
simon@ubuntu:~/mtgjson/node_modules$ cd ..
simon@ubuntu:~/mtgjson$ cd build
simon@ubuntu:~/mtgjson/build$ node buildSet.js ORI
Doing sets: ORI
====================================================================================================================
Ripping Set: Magic Origins
Getting card lists...
Magic Origins

/home/simon/mtgjson/node_modules/promise/index.js:47
                        throw "callback is not a function";
                        ^
callback is not a function

**Comment by lsmoura** [comment]
fsevents? I'm not using it directly. Maybe it's a submodule?

Look at the dependencies:

```javascript
  "dependencies": {
    "cache": "git+https://github.com/mtgjson/cache.git",
    "cli-color": ">= 0.2.3",
    "domino": ">= 1.0.19",
    "mhash": ">= 2.0.2",
    "moment": ">= 2.10.6",
    "rimraf": ">= 2.4.2",
    "tiptoe": ">= 1.0.0",
    "xbase": "git://github.com/Sembiance/xbase.git",
    "xutil": "git://github.com/Sembiance/xutil.git"
  }
```

**Comment by florentdouine** [comment]
Maybe this can help --> https://github.com/lsmoura/mtgjson/issues/140
