### ISSUE TITLE
Several cards are missing all theirs printings

### ISSUE THREAD

**Issue by Hologos** [lsmoura/mtgjson#136]
Hello, I'm building a project using MTG JSON and I found out that several cards are missing all theirs printings. For example Path to Exile is missing a FNM printing (http://magiccards.info/fnmp/en/182.html).

**Comment by bra1n** [comment]
The reason for this is that Gatherer doesn't [list any promotional printings](http://gatherer.wizards.com/Pages/Card/Printings.aspx?multiverseid=382192) and MTGJSON is based on Gatherer. The only way to fix this would be to take a secondary source for printings like these, which is probably not going to happen anytime soon.

**Comment by Hologos** [comment]
I see, didn't know that. Thank you.
