### ISSUE TITLE
For the card "Westvale Abbey" the multiverse ID is wrong for each side.

### ISSUE THREAD

**Issue by Sturmeh** [lsmoura/mtgjson#138]
Westvale Abbey should be 410050 and the flip side is 410049.

I'm not sure why this is the case, but that is the way it is on Gatherer.

**Comment by lsmoura** [comment]
Man... That card is giving me headaches.

If you go on 410049 you see first the picture of the land and the description of the creature, when you go to 410050 you see the opposite...

Every double-faced card ever released has first the mvid of the front first then the back side.

Also, when you search for "westvale", you see two cards. The prince and "Westvale cult leader". The card of the prince has id 410049, and I believe that the card picture is wrong.

I'll leave this as-is for now as I believe gatherer will be fixed at some point. Thank you for pointing it out but I'll wait a couple of weeks on this one.

**Comment by Sturmeh** [comment]
FYI, this has been fixed by WotC in gatherer @lsmoura .
