### ISSUE TITLE
CMC of double faced card is wrong in each set

### ISSUE THREAD

**Issue by MickHardins** [lsmoura/mtgjson#139]
Since wizard changed CMC cost rule for double faced cards, now this field is wrong in all sets that contains such type of cards. ( i've checked SOI - ISD and ORI , but i think it's wrong in each sets ) 

CMC field is missing in all double faced cards' back so as MTGJSON doc says. "Cards without this field have an implied cmc of zero as per rule 202.3a", but unfourtunately, this isn't true anymore. :) 

**Reference:**
http://magic.wizards.com/en/articles/archive/feature/shadows-over-innistrad-mechanics

**Comment by lsmoura** [comment]
Oh god... You're right. Back to the lab!
