### ISSUE TITLE
throw "callback is not a function" with new cache module

### ISSUE THREAD

**Issue by florentdouine** [lsmoura/mtgjson#140]
Hi sergio,

i've got an issue when i try to buildSet SOI. It seems like the function getUrlAsDoc doesn't call correctly the cache module in this bunch of code ->
``` javascript
exports.cache.get(
			targetURL,
			function(cachecb) {
				base.info("Requesting from web: %s", targetURL);
				downloadDoc(function(err, html) {
					if (err)
						throw(err);
					cachecb(html);
				})
			}
	).done(function(err, html) {
		if (err)
			throw (err);
		setImmediate(cb, null, domino.createWindow(html).document);
	});
```

I obtain this issue when i build : 
```bash
projets/mtgjson/node_modules/cache/node_modules/promise/index.js:47
			throw "callback is not a function";
			^
callback is not a function
```

Do you have the same problem on your side ? Do you have an idea of the source of the problem ?

Thanks for your help !

**Comment by florentdouine** [comment]
After a long time debugging, i just found that function : ``` fs.readFile(file, function(err, data){}); ``` doesn't return an error if file doesn't exist...
That's why i've got the error above.

I just change the line ``` if(err) ``` in cache/index.js with  ```if (err || !fs.exists(file)) ```

@lsmoura, i don't know how you want to handle this case. Please update this issue if you correct this ;)

**Comment by lsmoura** [comment]
> After a long time debugging, i just found that function : fs.readFile(file, function(err, data){}); doesn't return an error if file doesn't exist...

Wait... WHAT!? It SHOULD!!

**Comment by lsmoura** [comment]
Look:

```
$ node --version
v5.0.0

$ node
> fs.readFile('a file that does not exist', (err, data) => {
...   if (err) {
.....     console.error('There was an error reading the file!', err);
.....     return;
.....   }
...   // Otherwise handle the data
... });
undefined
> There was an error reading the file! { [Error: ENOENT: no such file or directory, open 'a file that does not exist']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'a file that does not exist' }
```

Script source: https://nodejs.org/api/errors.html

**Comment by peardox** [comment]
@lsmoura

This is something you recently added I guess as an new clone no longer works on Ubuntu

I'll patch mine and try against node 5.9.1 (latest stable)

To be honest I could just run this on my Mac but fixing something is better than just getting it working for myself (Ubuntu being the most popular Linux in the world)

**Comment by lsmoura** [comment]
@peardox I'll start tests on my debian...

**Comment by peardox** [comment]
What version of Debian?

I'll set up a VMWare box so I can run tests as well

**Comment by lsmoura** [comment]
Well, well...
It turns out that the SO was not the issue... I had updated the "promise" module locally but forgot to push to the repository. So my code was updated and nobody else was.

I've cloned it in my mac and I got an error. And i found out why... So, just NPM update and you should be good.

The Debian running on mtgjson server is:
```
Linux mtgjson.com 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u5 (2015-10-09) x86_64 GNU/Linux
```

**Comment by peardox** [comment]
Cool - I was just debugging the promise myself

I'll set up a Debian same as yours later

**Comment by peardox** [comment]
Yep - the update makes things tick over nicely

I'll build a few expansions to see how things go

I can write an Ubuntu guide for you now I know how to get it working if you like - I've been taking extensive notes

Prob worth trying on a Centos as well

**Comment by florentdouine** [comment]
Thanks @lsmoura 
I was sure to miss something on promise module ;)

I finally succeed a buildSet today !!

**Comment by lsmoura** [comment]
> I can write an Ubuntu guide for you now I know how to get it working if you like - I've been taking extensive notes

Can you just re-clone the repository, `npm update` and build a set to see how it goes?

**Comment by peardox** [comment]
I'm now getting some external errors

These are most likely from a load of us trying the same thing at the same time (too many builds at once)

If you re-run it messes up a bit later

I guess the best advice it wait 10 mins then try again to avoid throttling

Everything else is working perfectly with zero code changes on 5.9.1 (latest)

Error downloading: http://magiccards.info/ori/en/32.html
Error: socket hang up
    at createHangUpError (_http_client.js:239:15)
    at Socket.socketCloseListener (_http_client.js:271:23)
    at emitOne (events.js:95:20)
    at Socket.emit (events.js:182:7)
    at TCP._onclose (net.js:477:12)
/home/simon/api/mtgjson/shared/shared.js:653
                                        throw(err);
                                        ^

Error: socket hang up
    at createHangUpError (_http_client.js:239:15)
    at Socket.socketCloseListener (_http_client.js:271:23)
    at emitOne (events.js:95:20)
    at Socket.emit (events.js:182:7)
    at TCP._onclose (net.js:477:12)
simon@ubu:~/api/mtgjson/build$ node buildSet.js ORI
Doing sets: ORI

**Comment by peardox** [comment]
Yep - it's definitely flood protection

**Comment by peardox** [comment]
I know this is closed

I'll give you a day to respond or do it myself... It'll go something like this...

Dear MCI

Myself and a friend provide a valuable service to MTG fans as you can see at https://github.com/lsmoura/mtgjson

You appear to have added flood protection to your site

Could you either allow us to send a header letting you know its us doing good things for the community or allow us to mirror - if a mirror we'll do the same kinda thing our end.

We only need the HTML (correct me if I'm wrong Sergio)

I'm merely keeping this project alive, it has many, many followers. A highly popular GitHub resource.

If there's any way you can help us we'd love to talk
