### ISSUE TITLE
Promos

### ISSUE THREAD

**Issue by jenjia** [lsmoura/mtgjson#145]
Aren't Promos cards not updated anymore from http://magiccards.info/?

eg. Path to Exile for FNM
Shambling Vent for Prerelease Promos

edit: I mean, for what I know MTGJson gathers info from Gatherer and magiccards.info, right? if so, isn't it gathering the promo cards from magiccards.info anymore?

**Comment by lsmoura** [comment]
This is fixed on the latest release.
