### ISSUE TITLE
Add way to determine 'front' side of double-faced cards

### ISSUE THREAD

**Issue by Didero** [lsmoura/mtgjson#146]
There seems to be no way to retrieve which of the sides of a double-faced card is the front or starting side.
Currently it seems the 'names' field is sorted either alphabetically (e.g. 'Autumnal Gloom' / 'Ancient of the Equinox' in SOI, in this case it's the wrong way round), or by listing the current card second (e.g. 'Town Gossipmonger' / 'Incited Rabble' in SOI).
The best solution to me seems making sure that the 'names' field lists the front side first and the back side second, on both cards. This would also work for 'flip' cards.
Thanks for looking into this.

**Comment by lsmoura** [comment]
I'm updating SOI this weekend the order of double-faced cards names will be `[ front, back ]` it already is like this on the github repository.

Also, you can check the card number. if it ends with 'a', it's front face, if not is the back.
