### ISSUE TITLE
Madness: the reminder text is not up to date with old cards

### ISSUE THREAD

**Issue by mirandir** [lsmoura/mtgjson#147]
Hello,

The reminder text for madness has not been updated for the old cards in mtgjson.
For example, Fiery Temper in Time Spiral still has this reminder: "(If you discard this card, you may cast it for its madness cost instead of putting it into your graveyard.)"
In Shadows over Innistrad: (If you discard this card, discard it into exile. When you do, cast it for its madness cost or put it into your graveyard.)
On the Gatherer, the text is up to date for the two cards: http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=32918, http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=409908.

**Comment by lsmoura** [comment]
I'll have to rebuild the older sets for this one...
