### ISSUE TITLE
Welcome Deck 2016 has no release date

### ISSUE THREAD

**Issue by dgant** [lsmoura/mtgjson#148]
Welcome Deck 2016 has no releaseDate property. It's the only set that doesn't, including sets which just represent categories of cards like Media Inserts.

**Comment by lsmoura** [comment]
That's true. I couldn't find the release date. Do you know where it is?

**Comment by dgant** [comment]
http://magic.wizards.com/en/articles/archive/daily-magic-update/update-2016-03-25 -- Released May 13 2016

**Comment by SadisticMystic** [comment]
It also has no "type" field, which can lead to uninitialized value errors if you're trying to include or exclude sets of a particular type. Using Portal as precedent, it should probably have type "starter".

**Comment by fenhl** [comment]
The release date should be 2016-04-08 since two of the three products these cards appear in (the SOI Deck Builder's Toolkit as well as the intro decks new players get for free) were released along with SOI.
