### ISSUE TITLE
Foriysian Brigade (Weatherlight) Text Wrong

### ISSUE THREAD

**Issue by esb** [lsmoura/mtgjson#153]
MTGJSON: "Foriysian Brigade can block an additional creature."

Actual:  "Foriysian Brigade can block an additional creature each combat."

**Comment by leematos** [comment]
Good catch! @lsmoura, I ran this locally and my WTH.json has the updated text. I suspect an oracle change? Also @esb, what were you using All-sets.json or WTH.json?

**Comment by esb** [comment]
This was picked up from the All-Sets.json files.
The Oracle changes are all documented in the OGW Update Bulletin - http://magic.wizards.com/en/articles/archive/feature/oath-gatewatch-oracle-2016-01-29

**Comment by leematos** [comment]
@esb, cool, thanks! I wrote a fix, just hoping it can be merged. 👍
