### ISSUE TITLE
Shadow Rider (Weatherlight) Type Wrong

### ISSUE THREAD

**Issue by esb** [lsmoura/mtgjson#154]
Type is wrong. Changed from "Creature — Zombie Knight" to "Creature — Knight".

**Comment by leematos** [comment]
Is that wrong? It looks like that's what Gatherer has: 

http://gatherer.wizards.com/Pages/Card/Details.aspx?printed=false&multiverseid=4467

**Comment by esb** [comment]
Yes, the correct type is "Creature - Knight". It was changed from "Creature - Zombie Knight", and that value was in the AllSets file.

**Comment by lsmoura** [comment]
Fixed by acf9c3e75a7a72e4b751635d58d19147ee325b60
