### ISSUE TITLE
Commander 2013 - Missing "Skullwinder"

### ISSUE THREAD

**Issue by Garbee** [lsmoura/mtgjson#158]
The [Skullwinder](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=405384) card from Commander 2013 is missing from the API data.

**Comment by DragonXDoom** [comment]
Skullwinder was printed in Commander 2015, and is present in the API data.

**Comment by Garbee** [comment]
Ah, I had been told the incorrect printing when it was brought up.

Thanks @DragonXDoom. Now to sync the set to get it into our system.
