### ISSUE TITLE
change/add archive format

### ISSUE THREAD

**Issue by aeosynth** [lsmoura/mtgjson#167]
i'd like mtgjson to use an archive format which is more widely supported on linux systems. for example, gnu tar does not support the zip format, but it does support xz. i download the AllSets file in my project's build step, and i can't use the zipped file because i don't want to add a dependency on `unzip`.

**Comment by lsmoura** [comment]
There is a GZ version for all json files. Like so: http://mtgjson.com/json/ORI.json.gz
If that does not works for you, feel free to reopen the case.

**Comment by aeosynth** [comment]
lovely. can this be documented? i had no idea.

**Comment by lsmoura** [comment]
Actually... It isn't needed. The file is served trough http when you ask for a non-gz version (like http://mtgjson.com/json/ORI.json) and your browser accepts gzip compression (as possibly all browsers do).

If you just request the original file trough chrome, firefox, safari, opera, even wget they will retrieve the gzipped version and decompress it for you.

If your browser does not support gzip compression (or you explicitly asked that no compression should be done), you'll get the plain json file streamed for you (therefore using more bandwidth).

**Comment by aeosynth** [comment]
i use curl, and have to use the `--compressed` flag; otherwise i download the uncompressed version

interestingly, the `--compressed` .json download is 3.8m, while the .json.gz is 3.9
