### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by fenhl** [lsmoura/mtgjson#168]
I kind of need the fixed set info on W16 for a project. I've tried to build the database myself but I'm getting a lot of errors and am not familiar enough with node.js to fix them myself.

**Comment by dgant** [comment]
Eternal Masters just landed on Gatherer! http://gatherer.wizards.com/Pages/Search/Default.aspx?set=[%22Eternal%20Masters%22]

**Comment by lsmoura** [comment]
It's already on the repo. Fixing other sets. Website update coming later tonight!

**Comment by lsmoura** [comment]
Done.
