### ISSUE TITLE
Email address not working

### ISSUE THREAD

**Issue by fenhl** [lsmoura/mtgjson#169]
I've tried to send a message to the email address listed on the website, but the message was bounced. Is there currently a problem with the mail server or does the website simply have the wrong address?

**Comment by lsmoura** [comment]
My server is acting up (e-mail wise). Feel free to write me at **sergio at moura dot us**.
I'll be participating on a hackatron this weekend, I'll be back by monday.

**Comment by fenhl** [comment]
I was just trying to ask about a new release (#168).

**Comment by lsmoura** [comment]
It's working now. New release coming before June 10th.
