### ISSUE TITLE
KTK cards still appearing as standard-legal

### ISSUE THREAD

**Issue by cheyner** [lsmoura/mtgjson#171]
Hello, the "legalities" for cards in KTK are still listed as being standard-legal, despite having rotated out of standard with the release of SOI.

I observed this in the AllSets-x.json file.  Here's an example of a single card listing the legalities:
https://gist.github.com/cheyner/13bd4fef2c12133c6a7f0b4170dbd323

Thank you for maintaining this project!

**Comment by lsmoura** [comment]
This is fixed on the last release. Forgot to close it...
