### ISSUE TITLE
mtgjson/json/PD2.json Missing Card Data

### ISSUE THREAD

**Issue by ebmusicman84** [lsmoura/mtgjson#174]
It appears that the card data for set PD2 went missing in the push on April 11:

339374988e90342b4de42678b815545c28340646

**Comment by ebmusicman84** [comment]
Correction, it was present in the April 11 push, and is missing from the most recent push. 41ce033eed96c2bb4a2723f6e17e79e10ac6359f

**Comment by lsmoura** [comment]
Rebuilding public folder for webpage publishing.
