### ISSUE TITLE
small visual improvement to webpage - missing space

### ISSUE THREAD

**Issue by tooomm** [lsmoura/mtgjson#179]
![nospace](https://cloud.githubusercontent.com/assets/9874850/16005023/4a7272d4-3165-11e6-99a7-b5e4dc7a7e71.png)

There should be a simple space as separator between
`Current version:` and the `actual version number`

Change should be here?
https://github.com/lsmoura/mtgjson/blob/75a4caad3f7d7509c4d3d990c09b4fd8af314658/web/index.pug#L22-L25

**Comment by lsmoura** [comment]
Fixing this. Also found some missing spaces on the "thanks" section.

Thank you.
