### ISSUE TITLE
"Æ" errata

### ISSUE THREAD

**Issue by bottleofwater** [lsmoura/mtgjson#188]
The "Æ" character (as in "Ætherling")  [has been errata'd](http://markrosewater.tumblr.com/post/144471532728/this-is-a-bit-weird-but-i-notice-its-the-aether), so I feel like each card using it should see its name changed in order to reflect this update. Gatherer seems to got it wrong, tho, and still uses "Æ".

**Comment by dgant** [comment]
Has the errata officially been applied, yet?

I imagine the reason they're doing it is because of the upcoming set AEther Revolt, so they may not have applied the errata; they're just planning to.

**Comment by lsmoura** [comment]
Once this is in Gatherer, mtgjson will update.

**Comment by bottleofwater** [comment]
Changing the card names will probably break any database that used names as card ID (which was apparently fine, since names were assumed to be constant). Once the errata will roll, such systems won't be able to detect that two cards are actually the same ones, .and will have duplicated entries.

It might not be a big deal, and it's easy to find workaround for this, but maybe adding a "card id" could be considered. There's already one, but unfortunately it cannot be used since it depends on the card name too.

**Comment by Garbee** [comment]
The only solution is to have 100% unique identifiers is to have a system overhaul which uses a true database for the backend. That would in turn generate a UUID for each card in the store which would never change.

If your ID depends upon data in which it is related to storing, you're going to have a bad day since any data could be changed in the future. In theory, Wizards could errata Black Lotus to say it is now a 0/1 legendary artifact creature that has haste and is indestructible. Unlikely, but still possible.

**Comment by arcanis** [comment]
I've thought a bit about this issue, and I think that a database is not required. The only thing we need is to be able to successfully sort the cards by their printing. That doesn't look impossible, since we already know sets `releaseDate`, and card numbers. WDYT ?

**Comment by Garbee** [comment]
That isn't reasonable. Wizards can shift anything around which would cause an index to change. Any numbers can be modified, names refactored, even possibly an oracle on the casting cost of a card could be done. The only possibly-safe thing would be the gatherer id, however not everything has one so you can't use that as your unique thing to generate an identifier from.

The only reasonable solution for a long-term stable API is a database with a globally unique ID. Which, we do our absolute best to make sure the same card data is being updated for the proper item (weigh gatherer id highest against set code + collector number for accuracy in updating.)

**Comment by arcanis** [comment]
In order for an ID generated by such a system to change, a new set would have to be created between already existing set, or the number of cards in a set would have to change (or Wizards would have to change the release date of a set ;). Those events all seem extremely unlikely, or at the very least a lot more unlikely than the probability of a card name to change.

**Comment by Garbee** [comment]
Not necessarily change the number of cards. However they could go back and say add in tokens to Gatherer. Or change a number itself as the system is updated to handle the meld stuff better.
