### ISSUE TITLE
Add 'color identity'

### ISSUE THREAD

**Issue by Sembiance** [lsmoura/mtgjson#45]
A user requested the following: "Commander/EDH, and color identity is what determines what cards can go in your decks for Commander.  It refers to any colored mana symbol on the card, be it in the cost or text box.  So, Yasova is URG, Talisman of Dominance is UB, Karn, Silver Golem is 'Colorless', the Pacts and Evermind are their respective colors as indicated by their Color Indicator, etc.  Most cards are pretty straightforward, and just the color in the mana cost, but everything from Quagmire Druid to Memnarh to Lands (Sandsteppe Citadel) to Rattleclaw Mystic have color identities that differ than their casting cost. 

http://mtgcommander.net/rules.php has an explanation of color identity (the official source of commander info/rules); it's also addressed in the comprehensive rules at 903.4 (http://magiccards.info/rule/903-commander.html)."

**Comment by Psithief** [comment]
> * Reminder text is not included in the colour identity of a card.

This was added to ensure Extort does not contribute to colour identity. I don't believe any other cards are affected.

**Comment by lsmoura** [comment]
Just a heads-up: this is being worked on at the "commander" branch.
