### ISSUE TITLE
originalCardText has invalid activation costs in earlier cards

### ISSUE THREAD

**Issue by Sembiance** [lsmoura/mtgjson#48]
Many of the early 4th edtion and earlier cards have messed up activation costs in the 'originalCardText' field (such as '1oRooR' on gatherer for 1RR) and also missing colons for almost all of them. These are gatherer errors that I'll need to correct by hand and add to SET_CORRECTIONS (though some may be able to be fixed in an automated fashion if I can determine a pattern to the errors)

Being that these errors are in the originalCardText and not in the oracle 'text' the priority on fixing this issue is much lower

**Comment by Sembiance** [comment]
Some known issues:

Set: 4th Edition
Card: Cave People
Original Text Correction
MTGJSON: "When attacking, Cave People gets +1/-2 until end of turn.\n1{R}{R}, {T}: Target creature gains mountainwalk until end of turn."
Actual:  "When attacking, Cave People gets +1/-2 until end of turn.\n{1}{R}{R}, {T}: Target creature gains mountainwalk until end of turn."
------------------------------------------------------------------
Set: 4th Edition
Card: Ali Baba
Original Text Correction
MTGJSON: "{R} Tap target wall."
Actual:  "{R}: Tap target wall."
------------------------------------------------------------------
Set: 4th Edition
Card: BlessText ing
Original Correction
MTGJSON: "{W} Target creature Blessing enchants gets +1/+1 until end of turn."
Actual:  "{W}: Target creature Blessing enchants gets +1/+1 until end of turn."
------------------------------------------------------------------
Set: 4th Edition
Card: Brothers of Fire
Original Text Correction
MTGJSON: "1{R}{R} Brothers of Fire deals 1 damage to target creature or player and 1 damage to you."
Actual:  "{1}{R}{R}: Brothers of Fire deals 1 damage to target creature or player and 1 damage to you."
------------------------------------------------------------------
Set: 4th Edition
Card: Cave People
Original Text Correction
MTGJSON: "When attacking, Cave People gets +1/-2 until end of turn.\n1{R}{R}, {T}: Target creature gains mountainwalk until end of turn."
Actual:  "When attacking, Cave People gets +1/-2 until end of turn.\n{1}{R}{R}, {T}: Target creature gains mountainwalk until end of turn."
------------------------------------------------------------------
Set: 4th Edition
Card: Deathgrip
Original Text Correction
MTGJSON: "{B}{B} Counter target green spell. Play this ability as an interrupt."
Actual:  "{B}{B}: Counter target green spell. Play this ability as an interrupt."
------------------------------------------------------------------
Set: 4th Edition
Card: Dragon Whelp
Original Text Correction
MTGJSON: "Flying\n{R} +1/+0 until end of turn. If you spend more than {R}{R}{R} in this way during one turn, destroy Dragon Whelp at end of turn."
Actual:  "Flying\n{R}: +1/+0 until end of turn. If you spend more than {R}{R}{R} in this way during one turn, destroy Dragon Whelp at end of turn."
------------------------------------------------------------------
Set: 4th Edition
Card: Drudge Skeletons
Original Text Correction
MTGJSON: "{B} Regenerate"
Actual:  "{B}: Regenerate"
------------------------------------------------------------------
Set: 4th Edition
Card: Firebreathing
Original Text Correction
MTGJSON: "{R} Target creature Firebreathing enchants gets +1/+0 until end of turn."
Actual:  "{R}: Target creature Firebreathing enchants gets +1/+0 until end of turn."
------------------------------------------------------------------
Set: 4th Edition
Card: Flood
Original Text Correction
MTGJSON: "{U}{U} Tap target creature without flying."
Actual:  "{U}{U}: Tap target creature without flying."
------------------------------------------------------------------
Set: 4th Edition
Card: Frozen Shade
Original Text Correction
MTGJSON: "{B} +1/+1 until end of turn"
Actual:  "{B}: +1/+1 until end of turn"
------------------------------------------------------------------
Set: 4th Edition
Card: Ghost Ship
Original Text Correction
MTGJSON: "Flying\n{U}{U}{U} Regenerate"
Actual:  "Flying\n{U}{U}{U}: Regenerate"
------------------------------------------------------------------
Set: 4th Edition
Card: Goblin Balloon Brigade
Original Text Correction
MTGJSON: "{R} Flying until end of turn"
Actual:  "{R}: Flying until end of turn"
------------------------------------------------------------------
Set: 4th Edition
Card: Greed
Original Text Correction
MTGJSON: "{B} Pay 2 life to draw a card. Effects that prevent or redirect damage cannot be used to counter this loss of life."
Actual:  "{B}: Pay 2 life to draw a card. Effects that prevent or redirect damage cannot be used to counter this loss of life."
------------------------------------------------------------------
Set: 4th Edition
Card: Holy Armor
Original Text Correction
MTGJSON: "Target creature gets +0/+2.\n{W} Target creature Holy Armor enchants gets +0/+1 until end of turn."
Actual:  "Target creature gets +0/+2.\n{W}: Target creature Holy Armor enchants gets +0/+1 until end of turn."
------------------------------------------------------------------
Set: 4th Edition
Card: Hypnotic Specter
Flavour Text Correction
MTGJSON: "\"...There was no trace\nOf aught on that illumined face...\"\n—Samuel Coleridge, \"Phantom\""
Actual:  "\"...There was no trace\nOf aught on that illumined face....\"\n—Samuel Coleridge, \"Phantom\""
------------------------------------------------------------------
Set: 4th Edition
Card: Killer Bees
Original Text Correction
MTGJSON: "Flying\n{G} +1/+1 until end of turn"
Actual:  "Flying\n{G}: +1/+1 until end of turn"
------------------------------------------------------------------
Set: 4th Edition
Card: Pestilence
Original Text Correction
MTGJSON: "At the end of any turn, if there are no creatures in play, bury Pestilence.\n{B} Pestilence deals 1 damage to all creatures and players."
Actual:  "At the end of any turn, if there are no creatures in play, bury Pestilence.\n{B}: Pestilence deals 1 damage to all creatures and players."
------------------------------------------------------------------
Set: 4th Edition
Card: Regeneration
Original Text Correction
MTGJSON: "{G} Regenerate target creature Regeneration enchants."
Actual:  "{G}: Regenerate target creature Regeneration enchants."
------------------------------------------------------------------
Set: 4th Edition
Card: Shivan Dragon
Original Text Correction
MTGJSON: "Flying\n{R} +1/+0 until end of turn"
Actual:  "Flying\n{R}: +1/+0 until end of turn"
------------------------------------------------------------------
Set: 4th Edition
Card: The Brute
Original Text Correction
MTGJSON: "Target creature gets +1/+0.\n{R}{R}{R} Regenerate target creature The Brute enchants."
Actual:  "Target creature gets +1/+0.\n{R}{R}{R}: Regenerate target creature The Brute enchants."
------------------------------------------------------------------
Set: 4th Edition
Card: The Hive
Original Text Correction
MTGJSON: "5, {T}: Put a Wasp token into play. Treat this token as a 1/1 artifact creature with flying."
Actual:  "{5}, {T}: Put a Wasp token into play. Treat this token as a 1/1 artifact creature with flying."
------------------------------------------------------------------
Set: 4th Edition
Card: Uthden Troll
Original Text Correction
MTGJSON: "{R} Regenerate"
Actual:  "{R}: Regenerate"
------------------------------------------------------------------
Set: 4th Edition
Card: Vampire Bats
Original Text Correction
MTGJSON: "Flying\n{B} +1/+0 until end of turn. You cannot spend more than {B}{B} in this way each turn."
Actual:  "Flying\n{B}: +1/+0 until end of turn. You cannot spend more than {B}{B} in this way each turn."
------------------------------------------------------------------
Set: 4th Edition
Card: Wall of Bone
Original Text Correction
MTGJSON: "{B} Regenerate"
Actual:  "{B}: Regenerate"
------------------------------------------------------------------
Set: 4th Edition
Card: Wall of Brambles
Original Text Correction
MTGJSON: "{G} Regenerate"
Actual:  "{G}: Regenerate"
------------------------------------------------------------------
Set: 4th Edition
Card: Wall of Fire
Original Text Correction
MTGJSON: "{R} +1/+0 until end of turn"
Actual:  "{R}: +1/+0 until end of turn"
------------------------------------------------------------------
Set: 4th Edition
Card: Wall of Water
Original Text Correction
MTGJSON: "{U} +1/+0 until end of turn"
Actual:  "{U}: +1/+0 until end of turn"
------------------------------------------------------------------
Set: 4th Edition
Card: Will-o'-the-Wisp
Original Text Correction
MTGJSON: "Flying\n{B} Regenerate"
Actual:  "Flying\n{B}: Regenerate"
------------------------------------------------------------------
Set: 4th Edition
Card: Zombie Master
Original Text Correction
MTGJSON: "All zombies gain swampwalk and \n\"{B} Regenerate.\""
Actual:  "All zombies gain swampwalk and \n\"{B}: Regenerate.\""
------------------------------------------------------------------
Set: Arabian Nights
Card: Bottle of Suleiman
Original Text Correction
MTGJSON: "{4}: Flip a coin, with opponent calling heads or tails while coin is in the air. If the flip ends up in opponent's favor, Bottle of Suleiman does 5 damage to you. Otherwise, a 5/5 flying Djinn immediately comes into play on your side. Use a counter to represent Djinn. Djinn is treated exactly like a normal artifact creature except that if it leaves play it is removed from the game entirely. No matter how the flip turns out, Bottle of Suleiman is discarded after use."
Actual:  "{1}: Flip a coin, with opponent calling heads or tails while coin is in the air. If the flip ends up in opponent's favor, Bottle of Suleiman does 5 damage to you. Otherwise, a 5/5 flying Djinn immediately comes into play on your side. Use a counter to represent Djinn. Djinn is treated exactly like a normal artifact creature except that if it leaves play it is removed from the game entirely. No matter how the flip turns out, Bottle of Suleiman is discarded after use."

**Comment by esb** [comment]
I have a heap more of these sort of changes, which I can supply by set if you like.

For example, a few of the later sets have all the new line characters removed.

**Comment by Sembiance** [comment]
Gatherer is so awesome. Like 90% of the project is fixing Gatherer errors, bugs, issues, omissions and missing sets/cards.

I really appreciate @esb your offer to provide more errors, feel free to add them here on this issue, but I'm so not excited to fix them all :(

**Comment by lsmoura** [comment]
Bottle of Suleiman (Arabian Nights) is correct on MTGJson. I'm checking 4th edition now.
