### ISSUE TITLE
Magic 2015 Core Set not in Standard anymore

### ISSUE THREAD

**Issue by cscheid** [lsmoura/mtgjson#79]
I'm fairly sure Magic 2015 rotated out together with the Theros block, so with the updated legality change that brought BFZ into Standard, shouldn't M15 have been removed?

Examples:

    $ curl -sO http://mtgjson.com/json/AllCards-x.json
    $ jq '."Satyr Wayfinder".legalities | map(select(.format == "Standard"))' < AllCards-x.json
    [
      {
        "format": "Standard",
        "legality": "Legal"
      }
    ]

    $ jq '."Stoke the Flames".legalities | map(select(.format == "Standard"))' < AllCards-x.json
    [
      {
        "format": "Standard",
        "legality": "Legal"
      }
    ]

**Comment by Sembiance** [comment]
MTGJSON gets it's legalities from Gatherer, and Gatherer still lists those cards as standard legal.

**Comment by lsmoura** [comment]
This is fixed as of 0aca307599740ddbb5dbeed8d121de617ad3b21d. It will reflect changes on mtgjson.org shortly.
