### ISSUE TITLE
Create JSON file with latest updates/additions

### ISSUE THREAD

**Issue by Ypho** [lsmoura/mtgjson#80]
I'm using mtgjson.com to import all cards into my database. But sometimes updates are done or new cards are added. New cards for a new set for example have a new JSON file, which is no problem importing, just open the new file.

But sometimes older cards are updated, or cards are added (FNM, Promo's, Clash Packs), to prevent updating all sets by importing all JSON files again, it might be easier to have a file like latest_updates.json in which all updates/additions from the last week/month are placed. It makes it easier for users to automatically import that file each month into their database instead of scanning all files.

**Comment by Sembiance** [comment]
Have you seen: http://mtgjson.com/json/changelog.json

It lists which files have been changed and which new ones have been added.

**Comment by lsmoura** [comment]
I'm assuming the changelog.json file is what the user was looking for. Closing this one for the time being.
