### ISSUE TITLE
Improve legalities

### ISSUE THREAD

**Issue by Sembiance** [lsmoura/mtgjson#81]
Gatherer is often wrong or out of date when it comes to legalities.

For example see Issue #79 

I should probably calculate card legalities (at least for standard) automatically within MTGJSON instead of relying on Gatherer.

**Comment by lsmoura** [comment]
This is fixed as of 0aca307599740ddbb5dbeed8d121de617ad3b21d. It will reflect changes on mtgjson.org shortly.
