### ISSUE TITLE
Prettify JSON files for better Git change tracking

### ISSUE THREAD

**Issue by flyingmutant** [lsmoura/mtgjson#84]
Currently, all JSON files have all content on one line. This saves a bit of space, but makes it impossible to track changes across different versions using git. It would be better to format them with something like `json_reformat` from yajl in nice human-readable (and diff-friendly) way.

**Comment by flyingmutant** [comment]
For example, recent 97be48ce8922232e38326bd2639f06e01f233566 can not be easily inspected using either git or github.

**Comment by lsmoura** [comment]
I'm changing the format on mtgjson/json folder to a readable format using

```javascript
JSON.stringify(set, null, '  ');  // two spaces
```
The provided files on mtgjson.com website will still be a one-liner.

**Comment by flyingmutant** [comment]
Thanks a lot!

**Comment by lsmoura** [comment]
A followup to this issue: I'm implementing the sorting the "card keys", "legalities names" and "foreign language names" inside each card and sorting the cards array by the "number" parameter. The next set commit will have lots of changes, but the ones after that will have little impact.
