### ISSUE TITLE
remove ambiguity inside set.booster

### ISSUE THREAD

**Issue by arnehormann** [lsmoura/mtgjson#85]
Please change the array in `set.booster` to always contain arrays and not arrays or strings.
Removing that ambiguity makes life a lot easier for statically typed languages - in the Go sample from #74, the whole Rarity type can be replaced by `[]string`.
This may also block #71; I have no experience with json schema, but the schemas I know can't deal with more than one possible type at the same location - and the example from the [json-schema website](http://json-schema.org/examples.html) looks like it doesn't allow that, either.

**Comment by lsmoura** [comment]
How would you suggest to treat a "slot" that have more than one possibility (as is the case with rares / mythic rares)?

**Comment by arnehormann** [comment]
Some options:

First, most consistent and probably best is using arrays in every case - even for just one element.
Currently it can be `"single"` or `["option1", "option2"]`. Just change it to `["single"]` or `["option1", "option2"]`.

Alternatively you could use a named profile. Currently, there's only 20 different versions of filled `booster` fields. Just give each a name and reference it by that. Not so good for updates, but it should be ok.

Or you use short identifiers for each rarity and use these in a delimited string.
For example, 
`["rare" "uncommon" "uncommon" "common" "common" "common" "common" "common" "common" "common" "common" "timeshifted common" "timeshifted common" "timeshifted common" ["timeshifted rare","timeshifted uncommon"]]` could become `"r u u c c c c c c c c tc tc tc tr/tu"`.

Btw, when I tried this, I stumbled over an error in that part of my Go code. Will send a PR soon. The booster rarity resolution is a little convoluted...

**Comment by Garbee** [comment]
I don't feel anything should be done here. The delimited string setup is a nasty hack to suite only certain languages. The change overall would make things more difficult in languages where it isn't an issue. Since then, you'd need to splice and convert the string back into the full types.

This kind of change overall would make the JSON provided less legible.
