### ISSUE TITLE
Incorrect artist names for basic lands with multiple variations

### ISSUE THREAD

**Issue by flyingmutant** [lsmoura/mtgjson#89]
Previously, mtgjson was consistent with CCGHQ image releases (which were the basis for mtgimage). Namely, artist shows on image `SET/imageName.jpg` was the same as in the `artist` field of JSON. 

For BFZ at least, this is no longer true – artists from JSON and images differ for the majority of lands.

**Comment by lsmoura** [comment]
I don't really know what to do with this one... The names are generated procedurally and I'm not entirely sure I should be making manual additions to the imageName...

The algorithm used to create the names is the same as the one that was always used. Maybe CCGHQ is the one who changed the naming standard?

**Comment by lsmoura** [comment]
Ok. I'm wrong. I'll try to put my hands on the CCGHQ scans and fix the image names...

**Comment by lsmoura** [comment]
It's done, according to the CCGHQ image naming... There are two important points, tough:

* CCGHQ have only 5 (five) of each land. There are 10 (ten).
* I can't find an explanation for the order chosen by the CCGHQ team.

Other than that, it's done. If you find any issues on other sets, please open another issue and I'll check it out.

**Comment by flyingmutant** [comment]
Thanks a lot for all your work!

I've downloaded CCGHQ images, and there are 10 of each land. Do you want me to email you the link?

**Comment by lsmoura** [comment]
Yes, please! You can use my email address provided on mtgjson.com website.

**Comment by flyingmutant** [comment]
I've sent you an email.

**Comment by lsmoura** [comment]
It still differs form CCGHQ.
