### ISSUE TITLE
Add handle to Set

### ISSUE THREAD

**Issue by cjoudrey** [lsmoura/mtgjson#91]
Could be interesting to add a `handle` to each `Set` that follows [jninnes/mtgicons](https://github.com/jninnes/mtgicons/)'s convention.

That way it would be easy to render a set's icon by doing: `<i class="mtg #{handle}"></i>`

mtgicons' docs for reference: https://rawgit.com/jninnes/mtgicons/master/demo/demo.html

**Comment by cjoudrey** [comment]
Scratch that it prob makes more sense to just have mtgicons support set codes which I believe it does.

**Comment by flyingmutant** [comment]
Yeah, I agree — mtgicons should support mtgjson set codes, not the other way around.
