### ISSUE TITLE
Color Identity is wrong for split cards

### ISSUE THREAD

**Issue by tomato889** [lsmoura/mtgjson#94]
For example, Rise//Fall is ["U","B"] and ["B","R"], but should be ["U","B","R"] for both parts.

708.3. Each split card that consists of two halves with different colored mana symbols in their mana costs is a multicolored card while it’s not a spell on the stack. While it’s a spell on the stack, it’s only the color or colors of the half or halves being cast.
708.4. Although split cards have two castable halves, each split card is only one card. For example, a player who has drawn or discarded a split card has drawn or discarded one card, not two.

**Comment by lsmoura** [comment]
Yes. You're right. I was so worried about double-sided cards, that I forgot about split cards.

I'm on it.

**Comment by tomato889** [comment]
Cool, thanks. But I noticed that Cloistered Youth (double-faced) has "B" as its color identity, but it should be BW
